### PR TITLE
fix: fixing fee render logic

### PR DESCRIPTION
**Pull request by wainola**
## Description

Fix fee render using fee data on updated Fee object

## Related Issue Or Context

Closes: #146 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

### CODE REVIEW

**Comment by wainola** [comment]
update: waiting for this [issue](https://github.com/sygmaprotocol/sygma-explorer-indexer/issues/167) to be merged to update this PR.

**Review by LyonSsS — APPROVED** [review]
Validated on https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/explorer-ui/154

**Comment by LyonSsS** [comment]
Please update the displayed fee for Contract Call as well

**Comment by LyonSsS** [comment]
image
This is now fixed ( addressed)

**Comment by LyonSsS** [comment]
sygUSDC logic fee logic fixed 

Ignore the multiple decimals show for sygUSDC on EVM as it is set to 6 decimals currently ( same as substrate and the same as mainnet )

**Review by LyonSsS — APPROVED** [review]
This pass for QA

**Pull request merged**
