### PR TITLE
feat: refresh button and misc fixes

### PR DESCRIPTION
**Pull request by wainola**
## Description

This PR:

- adds refresh button to the explorer
- fix miscellaneous issues

## Related Issue Or Context

Closes: 
- #54 
- #50 
- #33 
- #41 
- #8
- #53 
- #52
- #55 
- #59 
- #51 
- #49 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

### CODE REVIEW

**Comment by mpetrun5** [comment]
Please fix build so the cloudflare deployment passes

**Comment by wainola** [comment]
> Please fix build so the cloudflare deployment passes. Also, specify what issues should this close.

Yeah, this should be draft still but I opened by mistake. Will do

**Review by FSM1 — APPROVED** [review]
Code looks good. Only issue I managed to find is that the transfer details page still shows the fee as plain text.
image

**Comment by mpetrun5** [comment]
> Code looks good. Only issue I managed to find is that the transfer details page still shows the fee as plain text. image

Aligning source transaction hash would be nice.
Also, value is is missing token info.

**Comment by mpetrun5** [comment]
The refresh button sizing is weird.
Please make it according to the design:
image

**Comment by wainola** [comment]
> Code looks good. Only issue I managed to find is that the transfer details page still shows the fee as plain text. image

Solved

**Review by MakMuftic — APPROVED** [review]

**Pull request merged**
